@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
Class Opciones{
    -opciones: Collection<String>
    +agregarOpcion(opcion: String): void
    +obtenerOpciones(): Collection<String>
    +compararConOrden(opciones: Opciones): boolean
    +compararSinOrden(opciones: Opciones): boolean
    +esta(opcion: String): boolean
}

Abstract Class Pregunta{
    -enunciado: String
    -tipoPenalidad: Penalidad
    -calificador: Calificador
    -exclusividad: Comodin
    +esCorrecta(Opcion: String): boolean
    +calificar(Respuestas: List<Respuesta>): void
    +asignarComodin(comodin: Comodin): void
}

Class Respuesta{
    -opcionesElegidas: Opciones
    -puntajeObtenido: Puntaje
    -multiplicador: Comodin
    +{static}Respuesta(jugador: Jugador)
    +{static}Respuesta(jugador: Jugador, multiplicador: Multiplicador)
    +agregarOpcion(opcion: String): void
    +agregarPuntajeObtenido(puntaje:Puntaje):void
    +aplicarComodin(): void
    +aplicarPuntaje(): void
}

Class Jugador{
    -nombre: String
    +{Static}Jugador(nombre: String)
    +modificarPuntaje(puntaje: puntaje): void
    +puntajeValorNumerico(): int
    +removerComodin(): Comodin
}

Interface IPunteable{
    +{abstract}agregar(puntaje: IPunteable): IPunteable
    +{abstract}valor(): int
}

Abstract Multiplicador{
    -factor: int
    +{static}Multiplicador(factor: int)
    -aplicar(puntaje: Puntaje): Puntaje
}

Interface Comodin{
    -aplicar(puntaje: Puntaje): Puntaje
}

Class Exclusividad{
    -aplicar(puntaje: Puntaje): Puntaje
}

Class MultiplicadorX2{
    -aplicar(puntaje: Puntaje): Puntaje
}

Class MultiplicadorX3{
    -aplicar(puntaje: Puntaje): Puntaje
}

'Relaciones
Respuesta o-- Jugador
Pregunta "1" *-left- "2" Opciones
Respuesta *-up- Opciones

Jugador *-- IPunteable

Jugador "1" *-left- "4" Comodin
Multiplicador --|> Comodin
Exclusividad --|> Comodin
MultiplicadorX2 --|> Multiplicador
MultiplicadorX3 --|> Multiplicador

@enduml