@startuml
Actor User
User -> HandlerBotonAccionarComidin: ActionEvent
activate HandlerBotonAccionarComidin
HandlerBotonAccionarComidin-> Juego: getInstancia()
activate Juego
Juego --> HandlerBotonAccionarComidin
deactivate Juego

HandlerBotonAccionarComidin -> Juego : aplicarComodin(comodinActual: Comodin)

activate Juego
Juego ->RondaActual:aplicarComodin(comodin:Comodin)
activate RondaActual
RondaActual ->turnoActual:aplicarComodin(pregunta,comodin)


deactivate Juego
deactivate RondaActual

@enduml