@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases

Class Panel{
    -rondas: List<Ronda>
    -jugador1: Jugador
    -jugador2: Jugador
    +jugar(jugador: Jugador, opcionesElegidas: Opciones): void
}

Class Ronda{
    -turnoActual: Turno
    -pregunta: Pregunta
    +jugar(jugador: Jugador, opcionesElegidas: Opciones): void
    +siguienteTurno(): void
}

Class Turno{
    +jugar(jugador: Jugador, opcionesElegidas: Opciones): void
}


'Relaciones
Panel "1" *-- "*" Ronda
Ronda "1" *-- "2" Turno

@enduml