@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
abstract Puntaje{
    +{abstract}agregar(puntaje: IPunteable): IPunteable
    +multiplicarPor(int factor): Puntaje
    +{abstract}valor(puntaje: Puntaje): int
}

Class Puntos{
    +agregar(puntaje: IPunteable): IPunteable
    +valor(): int
}

Abstract Class Punto{
    +agregar(puntaje: IPunteable): IPunteable
    +valor(): int
}

Class PuntoNulo{
    +valor(): int
}

Class PuntoNegativo{
    +valor(): int
}

Class PuntoPositivo{
    +valor(): int
}

'Relaciones
PuntoNegativo -up-|> Punto
PuntoNulo -up-|> Punto
PuntoPositivo -up-|> Punto
Puntos .up.|> Puntaje
Puntos o-up- "*" Puntaje
Punto .right.|> Puntaje
@enduml