@startuml
hide footbox
[->":ComparadorSinOrden":calificar(opcionesCorrectas,opcionesElegidas)
":ComparadorSinOrden"->"opcionesCorrectas:Opciones":compararSinOrden(opcionesElegidas:Opciones)
"opcionesCorrectas:Opciones"-->":ComparadorSinOrden": false
":ComparadorSinOrden"->"siguienteCalificador:CalificadorNoPenalizado":calificar(opcionesCorrectas,opcionesElegidas)

"siguienteCalificador:CalificadorNoPenalizado" --> ":ComparadorSinOrden": puntoNulo :PuntoNulo
[<--":ComparadorSinOrden": puntoNulo :PuntoNulo
@enduml