@startuml
hide footbox

[->":ComparadorSinOrden":calificar(opcionesCorrectas,opcionesElegidas)
":ComparadorSinOrden"->"opcionesCorrectas:Opciones":compararSinOrden(opcionesElegidas:Opciones)
"opcionesCorrectas:Opciones"-->":ComparadorSinOrden": true
[<--":ComparadorSinOrden": puntoPositivo :PuntoPositivo
@enduml