@startuml
Actor User
User -> ":HandlerBotonAccionarComidin": ActionEvent
activate ":HandlerBotonAccionarComidin"
":HandlerBotonAccionarComidin"-> ":Juego": getInstancia()
activate ":Juego"
":Juego" --> ":HandlerBotonAccionarComidin"
deactivate ":Juego"

":HandlerBotonAccionarComidin" -> ":Juego" : aplicarComodin(comodinActual: Comodin)

activate ":Juego"
":Juego" ->"RondaActual:Ronda":aplicarComodin(comodin:Comodin)
activate "RondaActual:Ronda"
"RondaActual:Ronda" ->"turnoActual:Turno":aplicarComodin(pregunta,comodin)


deactivate ":Juego"
deactivate "RondaActual:Ronda"

@enduml