@startuml

VoFClasicoPreguntaPregunta -> Penalidad:validar(comodin:Comodin)
activate VoFClasicoPregunta
activate Penalidad
Penalidad->Comodin:validar(this:Penalidad)
deactivate Penalidad
Pregunta ->Respuesta:setComodin(comodin:Comodin)
Pregunta ->Pregunta:agregarComodin(comodin :Comodin)
deactivate Pregunta


@enduml