@startuml
hide footbox
Actor User
User -> ":HandlerBotonAccionarComodin": ActionEvent
activate ":HandlerBotonAccionarComodin"
":HandlerBotonAccionarComodin"-> ":Juego": getInstancia()
activate ":Juego"
":Juego" --> ":HandlerBotonAccionarComodin"
deactivate ":Juego"

":HandlerBotonAccionarComodin" -> ":Juego" : aplicarComodin(comodinActual: Comodin)

activate ":Juego"
":Juego" ->"RondaActual:Ronda":aplicarComodin(comodin:Comodin)
activate "RondaActual:Ronda"
"RondaActual:Ronda" ->"turnoActual:Turno":aplicarComodin(pregunta,comodin)


deactivate ":Juego"
deactivate "RondaActual:Ronda"

@enduml