@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
Abstract Class Puntaje{
    +{abstract}añadir(puntaje: Puntaje): void
    +{abstract}valor(puntaje: Puntaje): int
}

Class Puntos{
    +añadir(puntaje: Puntaje): void
    +valor(): int
}

Class PuntoNulo{
    +añadir(puntaje: Puntaje): void
    +valor(): int
}

Class PuntoNegativo{
    +añadir(puntaje: Puntaje): void
    +valor(): int
}

Class PuntoPositivo{
    +añadir(puntaje: Puntaje): void
    +valor(): int
}

'Relaciones
PuntoNegativo -up-|> Puntaje
PuntoNulo -up-|> Puntaje
PuntoPositivo -up-|> Puntaje
Puntos -left-|> Puntaje
Puntos "1" o-left- "*" Puntaje

@enduml