@startuml

Package "Calificador"

Package "Penalidad"

Package "Puntaje"

Package "Opciones"

Package "Pregunta"

Package "Opciones"

Package "Respuesta"

Package "Jugador"

Package "Multiplicador"

Pregunta -right-> Calificador
Pregunta -down-> Penalidad
Pregunta -left-> Opciones
Respuesta -up-> Opciones
Respuesta --> Jugador
Jugador -right-> Multiplicador
Jugador --> Puntaje

@enduml