@startuml
rectangle RunTimeException
rectangle ErrorDeJugador
rectangle ErrorDePregunta
rectangle ErrorDePenalidad
rectangle TipoDePreguntaInvalida
rectangle MultiplicadorNoPermitido
rectangle ExclusividadNoPermitida
rectangle ComodinYaUsado
rectangle OpcionesCorrectasNoEstanEnOpcionesPosibles


RunTimeException <|-- ErrorDeJugador
RunTimeException <|-- ErrorDePregunta
RunTimeException <|-- ErrorDePenalidad
ErrorDeJugador <|-- ComodinYaUsado
ErrorDePenalidad <|--MultiplicadorNoPermitido
ErrorDePenalidad <|--ExclusividadNoPermitida
ErrorDePregunta <|-- TipoDePreguntaInvalida
ErrorDePregunta <|-- OpcionesCorrectasNoEstanEnOpcionesPosibles
@enduml