@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
abstract Puntaje{
    +{abstract}agregar(puntaje: Puntaje): Puntaje
    +{abstract}valorNumerico(puntaje: Puntaje): int
    +{abstract}vs(puntajeOponente: Puntaje): Puntaje
    +multiplicarPor(factor: int): Puntaje
}

Class Puntos{
    +agregar(puntaje: Puntaje): Puntaje
    +valorNumerico(): int
    +vs(puntajeOponente: Puntaje): Puntaje
}

Abstract Class Punto{
    +agregar(puntaje: Puntaje): Puntaje
    +{abstract}valorNumerico(): int
    +{abstract}vs(puntajeOponente: Puntaje): Puntaje
}

Class PuntoNulo{
    +valorNumerico(): int
    +vs(puntajeOponente: Puntaje): Puntaje
    +multiplicarPor(factor: int): Puntaje
}

Class PuntoNegativo{
    +valorNumerico(): int
    +vs(puntajeOponente: Puntaje): Puntaje
}

Class PuntoPositivo{
    +valorNumerico(): int
    +vs(puntajeOponente: Puntaje): Puntaje
}

'Relaciones
PuntoNegativo -down-|> Punto
PuntoNulo -down-|> Punto
PuntoPositivo -up-|> Punto
Puntos -up-|> Puntaje
Puntos o-up- "*" Puntaje
Punto -right-|> Puntaje
@enduml